# Generated by Django 4.2.3 on 2023-07-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_friend_playlist_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fav_genre',
            field=models.CharField(max_length=128),
        ),
    ]
