# Generated by Django 4.2.3 on 2023-07-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_user_fav_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fav_genre',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.IntegerField(default=0),
        ),
    ]
