# Generated by Django 4.2.3 on 2023-07-12 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_user_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='email',
        ),
    ]
