# Generated by Django 4.2.3 on 2023-07-12 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_rename_username_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='username',
        ),
    ]
